/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.myapp;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.MongoClient;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author Acer
 */
public class loginUser extends javax.swing.JFrame {

    DBCollection table;
    DB db;

    public loginUser() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("TH Sarabun New", 1, 36)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("TH Sarabun New", 1, 36)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 317, 40));

        btn_login.setBackground(new java.awt.Color(255, 204, 51));
        btn_login.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 110, -1));

        btn_back.setBackground(new java.awt.Color(255, 204, 51));
        btn_back.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        btn_back.setText("Back");
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 110, 40));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 320, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        BasicDBObject document = new BasicDBObject();
        MongoClient mongo;
        try {
            mongo = new MongoClient("localhost", 27017);
            db = mongo.getDB("mini");
            table = db.getCollection("users");
            document.put("Username", txt_username.getText());
            document.put("Password", txt_password.getText());
            document.put("Status", "Driver");

            DBCursor cc = table.find();
            DBCursor cursor = table.find(document);
            boolean b = false, d = false, a = false;
            while (cc.hasNext()) {
                String Row = cc.next().toString();
                JSONObject obj = new JSONObject(Row);

                //เช็คสถานะก่อนเข้าระบบ
                if (obj.getString("Status").equals("Driver")) {
                    int c = table.find(document).count();
                    if (c > 0) {
                        JOptionPane.showMessageDialog(null, "เข้าสู่ระบบเรียบร้อย");
                        queueUser qu = new queueUser(cursor.next().toString());
                        //queuUserDB quDB= new queuUserDB(cursor.next().toString());
                        d = true;
                        qu.show();
                        this.hide();
                        break;

                    }

                } else if (txt_username.getText().isEmpty() && txt_password.getText().isEmpty()) {
                    a = true;
                } else if (txt_username.getText().isEmpty() || txt_password.getText().isEmpty()) {
                    a = true;

                } else {
                    if (obj.getString("Status").equals("Admin")) {
                        if (b == false) {
                            b = true;

                        }
                    }
                }
            }
            if (d == false) {
                if (b == true) {
                    JOptionPane.showMessageDialog(null, "Register Please!!");
                }
                txt_username.setText(null);
                txt_password.setText(null);
            }
            if (a == true) {
                JOptionPane.showMessageDialog(null, "โปรดใส่ Username และ Password");
            }

        } catch (UnknownHostException e) {

        }
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
